### ISSUE TITLE
Jess broken or something is missing from the instructions in the README.md?

### ISSUE THREAD

**Issue by giacecco** [OpenAddressesUK/jess#3]
I've tried using Jess with:

```
{
  "saon": null,
  "paon": 22,
  "street": "Greenway",
  "locality": null,
  "town": "Berkhamsted",
  "postcode": "HP4 3JD"
}
```

I get back:

```
{"addresses":{"inferred":[],"existing":[]}}
```

... but we have addresses there: https://alpha.openaddressesuk.org/addresses.json?postcode=hp43jd . What am I doing wrong?

Ta.

**Comment by pezholio** [comment]
It's case sensitive at the mo, try:

``` JSON
{
  "saon": null,
  "paon": 22,
  "street": "GREENWAY",
  "locality": null,
  "town": "BERKHAMSTEAD",
  "postcode": "HP4 3JD"
}
```

**Comment by giacecco** [comment]
Ha! We should change that, very counterintuitive. We publish everything uppercase, what's the point of case sensitiveness in managing input? :-)

**Comment by pezholio** [comment]
I'm fixing as we speak :+1:
